// This file is automatically generated from your CSS. Any edits will be overwritten.
export const list: string;
export const listHeaderContainer: string;
export const listHeader: string;
export const listContent: string;
export const listHeaderItem: string;
export const listHeaderItemText: string;
