// This file is automatically generated from your CSS. Any edits will be overwritten.
export const header: string;
export const active: string;
export const search: string;
export const searchIcon: string;
export const searchInput: string;
