// This file is automatically generated from your CSS. Any edits will be overwritten.
export const form: string;
export const form__input: string;
export const formInput: string;
export const button: string;
